<template>
  <div>
    <p>tabs的文档</p>
    <p>tabs的文档</p>
    <p>tabs的文档</p>
    <p>tabs的文档</p>
    <p>tabs的文档</p>
    <p>tabs的文档</p>
    <p>tabs的文档</p>
    <p>tabs的文档</p>
    <p>tabs的文档</p>
    <p>tabs的文档</p>
    <p>tabs的文档</p>
    <p>tabs的文档</p>
    <p>tabs的文档</p>
    <p>tabs的文档</p>
    <p>tabs的文档</p>

  </div>
</template>